<?php
namespace TPWeb\Iban\Country;

use TPWeb\Iban\Country\Country;

class Belgium extends Country
{
    public $country_code = "BE";
    public $country_name = "Belgium";
    public $domestic_example = "539-0075470-34";
    public $bban_example = "539007547034";
    public $bban_format_swift = "3!n7!n2!n";
    public $bban_format_regex = "^(\d{3})(\d{7})(\d{2})$";
    public $bban_length = 12;
    public $iban_example = "BE68539007547034";
    public $iban_format_swift = "BE2!n3!n7!n2!n";
    public $iban_format_regex = "^BE(\d{2})(\d{3})(\d{7})(\d{2})$";
    public $iban_length = 16;
    public $bban_bankid_start_offset = 0;
    public $bban_bankid_stop_offset = 2;
    public $bban_branchid_start_offset = "";
    public $bban_branchid_stop_offset = "";
    public $registry_edition = "2011-06-20";
    public $country_sepa = 1;
    public $swift_official = 1;
    public $bban_checksum_start_offset = 10;
    public $bban_checksum_stop_offset = 11;
    public $country_code_iana = "be";
    public $country_code_iso3166_1_alpha2 = "BE";
    public $parent_registrar = "";
    public $currency_iso4217 = "EUR";
    public $central_bank_url = "www.nbb.be";
    public $central_bank_name = "National Bank of Belgium";
    
    public function calculateBic($iban) {
        //https://www.nbb.be/doc/be/be/protocol/wijzigingen_aan_de_lijst_van_bankidentificatiecodes.pdf
        $controle = substr($iban, 4, 3);
        $list = [];
        $list[] = ['min' => 000, 'max' => 000, 'bic' => 'BPOT BE B1', 'bank' => 'bpost bank'];
        $list[] = ['min' => 001, 'max' => 049, 'bic' => 'GEBA BE BB', 'bank' => 'BNP Paribas Fortis'];
        $list[] = ['min' => 050, 'max' => 099, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
        $list[] = ['min' => 100, 'max' => 101, 'bic' => 'NBBE BE BB 203', 'bank' => 'Nationale Bank van België'];
        $list[] = ['min' => 102, 'max' => 102, 'bic' => 'nav', 'bank' => 'Uitwisselingscentrum en Verrekening (U.C.V.)'];
        $list[] = ['min' => 103, 'max' => 108, 'bic' => 'NICA BE BB', 'bank' => 'Crelan'];
        $list[] = ['min' => 109, 'max' => 110, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
        $list[] = ['min' => 111, 'max' => 111, 'bic' => 'ABER BE 22', 'bank' => 'ABK Bank'];
//         $list[] = ['min' => 112, 'max' => 112, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 113, 'max' => 114, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
//         $list[] = ['min' => 115, 'max' => 115, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 116, 'max' => 116, 'bic' => 'VRIJ', 'bank' => 'Beleggings- en Kredietkantoor voor de Middenstand (in verreffening)'];
//         $list[] = ['min' => 117, 'max' => 118, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 119, 'max' => 124, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
        $list[] = ['min' => 125, 'max' => 126, 'bic' => 'CPHB BE 75', 'bank' => 'Banque CPH'];
        $list[] = ['min' => 127, 'max' => 127, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
//         $list[] = ['min' => 128, 'max' => 128, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 129, 'max' => 129, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
//         $list[] = ['min' => 130, 'max' => 130, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 131, 'max' => 131, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
        $list[] = ['min' => 132, 'max' => 132, 'bic' => 'BNAG BE BB', 'bank' => 'Bank Nagelmackers'];
        $list[] = ['min' => 133, 'max' => 134, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
//         $list[] = ['min' => 135, 'max' => 136, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 137, 'max' => 137, 'bic' => 'GEBA BE BB', 'bank' => 'BNP Paribas Fortis'];
        $list[] = ['min' => 138, 'max' => 138, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
//         $list[] = ['min' => 139, 'max' => 139, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 140, 'max' => 149, 'bic' => 'GEBA BE BB', 'bank' => 'BNP Paribas Fortis'];
        $list[] = ['min' => 150, 'max' => 150, 'bic' => 'BCMC BE BB', 'bank' => 'Bancontact - Mister Cash NV/SA'];
//         $list[] = ['min' => 151, 'max' => 170, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 171, 'max' => 171, 'bic' => 'CPHB BE 75', 'bank' => ''];
        $list[] = ['min' => 172, 'max' => 173, 'bic' => 'RABO BE 23', 'bank' => 'Coöperatieve Rabobank U.A.'];
//         $list[] = ['min' => 174, 'max' => 174, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 175, 'max' => 175, 'bic' => 'NAV', 'bank' => ''];
        $list[] = ['min' => 176, 'max' => 177, 'bic' => 'BSCH BE BR', 'bank' => 'Banco Santander'];
        $list[] = ['min' => 178, 'max' => 179, 'bic' => 'COBA BE BX', 'bank' => 'Commerzbank'];
//         $list[] = ['min' => 180, 'max' => 182, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 183, 'max' => 183, 'bic' => 'BARB BE BB', 'bank' => 'Bank of Baroda'];
//         $list[] = ['min' => 184, 'max' => 184, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 185, 'max' => 185, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
//         $list[] = ['min' => 186, 'max' => 188, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 189, 'max' => 189, 'bic' => 'SMBC BE BB', 'bank' => 'Sumitomo Mitsui Banking Corporation (SMBC)'];
        $list[] = ['min' => 190, 'max' => 199, 'bic' => 'CREG BE BB', 'bank' => ''];
        $list[] = ['min' => 200, 'max' => 214, 'bic' => 'GEBA BE BB', 'bank' => 'BNP Paribas Fortis'];
//         $list[] = ['min' => 215, 'max' => 219, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 220, 'max' => 298, 'bic' => 'GEBA BE BB', 'bank' => 'BNP Paribas Fortis'];
        $list[] = ['min' => 299, 'max' => 299, 'bic' => 'BPOT BE B1', 'bank' => 'bpost bank'];
        $list[] = ['min' => 300, 'max' => 399, 'bic' => 'BBRU BE BB', 'bank' => 'ING België'];
        $list[] = ['min' => 400, 'max' => 499, 'bic' => 'KRED BE BB', 'bank' => 'KBC Bank'];
//         $list[] = ['min' => 500, 'max' => 500, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 501, 'max' => 501, 'bic' => 'DHBN BE BB', 'bank' => 'Demir-Halk Bank (Nederland) (DHB)'];
//         $list[] = ['min' => 502, 'max' => 504, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 505, 'max' => 506, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 507, 'max' => 507, 'bic' => 'DIER BE 21', 'bank' => 'Dierickx, Leys & Cie Effectenbank'];
        $list[] = ['min' => 508, 'max' => 508, 'bic' => 'PARB BE BZ MDC', 'bank' => 'BNP Paribas Securities Services'];
        $list[] = ['min' => 509, 'max' => 509, 'bic' => 'ABNA BE 2A IPC', 'bank' => 'ABN AMRO Bank N.V.'];
        $list[] = ['min' => 510, 'max' => 510, 'bic' => 'VAPE BE 21', 'bank' => 'van de Put & Co Effectenbank'];
        $list[] = ['min' => 511, 'max' => 511, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 512, 'max' => 512, 'bic' => 'DNIB BE 21', 'bank' => 'NIBC BANK'];
        $list[] = ['min' => 513, 'max' => 513, 'bic' => 'SGPB BE 99', 'bank' => ''];
        $list[] = ['min' => 514, 'max' => 514, 'bic' => 'PUIL BE BB', 'bank' => 'Puilaetco Dewaay Private Bankers'];
        $list[] = ['min' => 515, 'max' => 515, 'bic' => 'IRVT BE BB', 'bank' => 'The Bank of New York Mellon NV/SA'];
//         $list[] = ['min' => 516, 'max' => 516, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 517, 'max' => 517, 'bic' => 'FORD BE 21', 'bank' => 'FCE Bank'];
        $list[] = ['min' => 518, 'max' => 518, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 519, 'max' => 519, 'bic' => 'BNYM BE BB', 'bank' => 'The Bank of New York Mellon'];
//         $list[] = ['min' => 520, 'max' => 520, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 521, 'max' => 521, 'bic' => 'FVLB BE 22', 'bank' => 'F. van Lanschot Bankiers'];
        $list[] = ['min' => 522, 'max' => 522, 'bic' => 'UTWB BE BB', 'bank' => 'United Taiwan Bank'];
        $list[] = ['min' => 523, 'max' => 523, 'bic' => 'TRIO BE BB', 'bank' => 'Triodos Bank'];
        $list[] = ['min' => 524, 'max' => 524, 'bic' => 'WAFA BE BB', 'bank' => 'Attijariwafa bank Europe'];
        $list[] = ['min' => 525, 'max' => 525, 'bic' => 'FVLB BE 2E', 'bank' => 'F. van Lanschot Bankiers'];
//         $list[] = ['min' => 526, 'max' => 529, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 530, 'max' => 530, 'bic' => 'SHIZ BE BB', 'bank' => 'Shizuoka Bank (Europe)'];
        $list[] = ['min' => 531, 'max' => 531, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
//         $list[] = ['min' => 532, 'max' => 534, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 535, 'max' => 535, 'bic' => 'FBHL BE 22', 'bank' => 'CREDIT EUROPE BANK NV'];
//         $list[] = ['min' => 536, 'max' => 537, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 538, 'max' => 538, 'bic' => 'nav', 'bank' => 'Hoist Finance'];
        $list[] = ['min' => 539, 'max' => 539, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 540, 'max' => 540, 'bic' => 'UBIN BE 22', 'bank' => 'Union Bank of India'];
        $list[] = ['min' => 541, 'max' => 541, 'bic' => 'BKID BE 22', 'bank' => 'BANK OF INDIA'];
//         $list[] = ['min' => 542, 'max' => 544, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 545, 'max' => 545, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 546, 'max' => 546, 'bic' => 'WAFA BE BB', 'bank' => 'Attijariwafa bank Europe'];
//         $list[] = ['min' => 547, 'max' => 547, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 548, 'max' => 548, 'bic' => 'LOCY BE BB', 'bank' => 'Lombard Odier (Europe)'];
        $list[] = ['min' => 549, 'max' => 549, 'bic' => 'CHAS BE BX', 'bank' => 'JP Morgan Chase Bank'];
        $list[] = ['min' => 550, 'max' => 560, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
        $list[] = ['min' => 561, 'max' => 561, 'bic' => 'FTNO BE B1', 'bank' => 'FORTUNEO BELGIUM'];
        $list[] = ['min' => 562, 'max' => 569, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
        $list[] = ['min' => 570, 'max' => 579, 'bic' => 'CITI BE BX', 'bank' => 'Citibank Europe Plc - Belgium Branch'];
//         $list[] = ['min' => 580, 'max' => 580, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 581, 'max' => 581, 'bic' => 'MHCB BE BB', 'bank' => 'Mizuho Bank Nederland N.V. Brussels Branch'];
//         $list[] = ['min' => 582, 'max' => 582, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 583, 'max' => 583, 'bic' => 'DEGR BE BB', 'bank' => ''];
        $list[] = ['min' => 584, 'max' => 584, 'bic' => 'ICIC GB 2L', 'bank' => 'ICICI Bank UK Limited'];
        $list[] = ['min' => 585, 'max' => 585, 'bic' => 'RCBP BE BB', 'bank' => ''];
        $list[] = ['min' => 586, 'max' => 586, 'bic' => 'CFFR BE B1', 'bank' => ''];
        $list[] = ['min' => 587, 'max' => 587, 'bic' => 'BIBL BE 21', 'bank' => 'BinckBank'];
        $list[] = ['min' => 588, 'max' => 588, 'bic' => 'CMCI BE B1 BTB', 'bank' => 'Banque Transatlantique Belgium'];
//         $list[] = ['min' => 589, 'max' => 589, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 590, 'max' => 594, 'bic' => 'BSCH BE BB', 'bank' => 'Santander Benelux'];
        $list[] = ['min' => 595, 'max' => 601, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
        $list[] = ['min' => 602, 'max' => 602, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
//         $list[] = ['min' => 603, 'max' => 604, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 605, 'max' => 605, 'bic' => 'BKCH BE BB', 'bank' => 'Bank of China (Luxembourg) S.A., Brussels Branch'];
//         $list[] = ['min' => 606, 'max' => 606, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 607, 'max' => 607, 'bic' => 'ICBK BE BB', 'bank' => 'Industrial and Commercial Bank of China (Europe)'];
//         $list[] = ['min' => 608, 'max' => 608, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 609, 'max' => 609, 'bic' => 'NAV', 'bank' => ''];
        $list[] = ['min' => 610, 'max' => 613, 'bic' => 'DEUT BE BE', 'bank' => 'Deutsche Bank AG'];
//         $list[] = ['min' => 614, 'max' => 614, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 615, 'max' => 622, 'bic' => 'BBRU BE BB', 'bank' => 'ING België'];
//         $list[] = ['min' => 623, 'max' => 623, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 624, 'max' => 625, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
//         $list[] = ['min' => 626, 'max' => 629, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 630, 'max' => 631, 'bic' => 'BBRU BE BB', 'bank' => 'ING België'];
//         $list[] = ['min' => 632, 'max' => 633, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 634, 'max' => 636, 'bic' => 'BNAG BE BB', 'bank' => 'Bank Nagelmackers'];
//         $list[] = ['min' => 637, 'max' => 637, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 638, 'max' => 638, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
        $list[] = ['min' => 639, 'max' => 639, 'bic' => 'ABNA BE 2A MYO', 'bank' => 'ABN AMRO Bank N.V.'];
        $list[] = ['min' => 640, 'max' => 640, 'bic' => 'ADIA BE 22', 'bank' => 'KBC Bank N.V. Business Center Diamant'];
//         $list[] = ['min' => 641, 'max' => 641, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 642, 'max' => 642, 'bic' => 'BBVA BE BB', 'bank' => 'Banco Bilbao Vizcaya Argentaria'];
        $list[] = ['min' => 643, 'max' => 643, 'bic' => 'BMPB BE BB', 'bank' => 'Banca Monte Paschi Belgio'];
//         $list[] = ['min' => 644, 'max' => 644, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 645, 'max' => 645, 'bic' => 'JVBA BE 22', 'bank' => 'Bank J. Van Breda & C°'];
        $list[] = ['min' => 646, 'max' => 647, 'bic' => 'BNAG BE BB', 'bank' => 'Bank Nagelmackers'];
//         $list[] = ['min' => 648, 'max' => 648, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
//         $list[] = ['min' => 649, 'max' => 649, 'bic' => 'nav', 'bank' => ''];
//         $list[] = ['min' => 650, 'max' => 650, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 651, 'max' => 651, 'bic' => 'KEYT BE BB', 'bank' => 'Keytrade Bank'];
        $list[] = ['min' => 652, 'max' => 652, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
//         $list[] = ['min' => 653, 'max' => 655, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 656, 'max' => 656, 'bic' => 'ETHI BE BB', 'bank' => 'OPTIMA BANK'];
        $list[] = ['min' => 657, 'max' => 657, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
        $list[] = ['min' => 658, 'max' => 658, 'bic' => 'HABB BE BB', 'bank' => 'Habib Bank'];
//         $list[] = ['min' => 659, 'max' => 662, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 663, 'max' => 663, 'bic' => 'BMEU BE B1', 'bank' => 'BMCE Euro Services'];
        $list[] = ['min' => 664, 'max' => 664, 'bic' => 'BCDM BE BB', 'bank' => 'Banque Chaabi du Maroc'];
        $list[] = ['min' => 665, 'max' => 665, 'bic' => 'SPAA BE 22', 'bank' => 'Crelan'];
        $list[] = ['min' => 666, 'max' => 666, 'bic' => 'nav', 'bank' => 'WORLDLINE NV'];
//         $list[] = ['min' => 667, 'max' => 667, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 668, 'max' => 668, 'bic' => 'SBIN BE 2X', 'bank' => 'State Bank of India'];
        $list[] = ['min' => 669, 'max' => 669, 'bic' => 'nav', 'bank' => 'WORLDLINE NV'];
        $list[] = ['min' => 670, 'max' => 670, 'bic' => 'NYA', 'bank' => 'CNH Industrial Capital EUROPE'];
        $list[] = ['min' => 671, 'max' => 671, 'bic' => 'EURB BE 99', 'bank' => 'Europabank'];
        $list[] = ['min' => 672, 'max' => 672, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
        $list[] = ['min' => 673, 'max' => 673, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
        $list[] = ['min' => 674, 'max' => 674, 'bic' => 'ABNA BE 2A IDJ', 'bank' => 'ABN AMRO Bank N.V.'];
        $list[] = ['min' => 675, 'max' => 675, 'bic' => 'BYBB BE BB', 'bank' => 'Byblos Bank Europe'];
        $list[] = ['min' => 676, 'max' => 676, 'bic' => 'DEGR BE BB', 'bank' => 'Bank Degroof Petercam'];
        $list[] = ['min' => 677, 'max' => 677, 'bic' => 'CBPX BE 99', 'bank' => ''];
        $list[] = ['min' => 678, 'max' => 678, 'bic' => 'DELE BE 22', 'bank' => 'Delen Private Bank'];
        $list[] = ['min' => 679, 'max' => 679, 'bic' => 'PCHQ BE BB', 'bank' => 'bpost'];
        $list[] = ['min' => 680, 'max' => 680, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
//         $list[] = ['min' => 681, 'max' => 681, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 682, 'max' => 683, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
//         $list[] = ['min' => 684, 'max' => 684, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 685, 'max' => 686, 'bic' => 'BOFA BE 3X', 'bank' => 'Bank of Amerika Merrill Lynch International Ltd'];
        $list[] = ['min' => 687, 'max' => 687, 'bic' => 'MGTC BE BE', 'bank' => 'Euroclear Bank'];
        $list[] = ['min' => 688, 'max' => 688, 'bic' => 'SGAB BE B2', 'bank' => 'Société Générale (Paris)'];
//         $list[] = ['min' => 689, 'max' => 689, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 690, 'max' => 690, 'bic' => 'BNPA BE BB', 'bank' => 'BNP Paribas'];
//         $list[] = ['min' => 691, 'max' => 692, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 693, 'max' => 693, 'bic' => 'BOTK BE BX', 'bank' => 'MUFG Bank (Europe)'];
        $list[] = ['min' => 694, 'max' => 694, 'bic' => 'DEUT BE BE', 'bank' => 'Deutsche Bank AG'];
//         $list[] = ['min' => 695, 'max' => 695, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 696, 'max' => 696, 'bic' => 'CRLY BE BB', 'bank' => 'Crédit Agricole Corporate & Investment Bank'];
//         $list[] = ['min' => 697, 'max' => 697, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 698, 'max' => 698, 'bic' => 'NATX BE B1', 'bank' => 'Natixis Bank'];
//         $list[] = ['min' => 699, 'max' => 699, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 700, 'max' => 709, 'bic' => 'AXAB BE 22', 'bank' => 'AXA Bank Europe'];
        $list[] = ['min' => 710, 'max' => 718, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 719, 'max' => 719, 'bic' => 'ABNA BE 2A XXX', 'bank' => 'ABN AMRO Bank N.V.'];
        $list[] = ['min' => 720, 'max' => 721, 'bic' => 'ABNA BE BR', 'bank' => 'The Royal Bank of Scotland Plc, Belgium branch'];
        $list[] = ['min' => 722, 'max' => 722, 'bic' => 'ABNA BE 2A IPC', 'bank' => 'ABN AMRO Bank N.V.'];
        $list[] = ['min' => 723, 'max' => 724, 'bic' => 'ABNA BE BR', 'bank' => 'The Royal Bank of Scotland Plc, Belgium branch'];
        $list[] = ['min' => 725, 'max' => 727, 'bic' => 'KRED BE BB', 'bank' => 'KBC Bank'];
        $list[] = ['min' => 728, 'max' => 729, 'bic' => 'CREG BE BB', 'bank' => ''];
        $list[] = ['min' => 730, 'max' => 731, 'bic' => 'KRED BE BB', 'bank' => 'KBC Bank'];
        $list[] = ['min' => 732, 'max' => 732, 'bic' => 'CREG BE BB', 'bank' => ''];
        $list[] = ['min' => 733, 'max' => 741, 'bic' => 'KRED BE BB', 'bank' => 'KBC Bank'];
        $list[] = ['min' => 742, 'max' => 742, 'bic' => 'CREG BE BB', 'bank' => ''];
        $list[] = ['min' => 743, 'max' => 749, 'bic' => 'KRED BE BB', 'bank' => 'KBC Bank'];
        $list[] = ['min' => 750, 'max' => 774, 'bic' => 'AXAB BE 22', 'bank' => 'AXA Bank Europe'];
        $list[] = ['min' => 775, 'max' => 799, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
        $list[] = ['min' => 800, 'max' => 816, 'bic' => 'AXAB BE 22', 'bank' => 'AXA Bank Europe'];
        $list[] = ['min' => 817, 'max' => 817, 'bic' => 'ISAE BE BB', 'bank' => 'CACEIS Bank Luxembourg'];
//         $list[] = ['min' => 818, 'max' => 822, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 823, 'max' => 823, 'bic' => 'BLUX BE 41', 'bank' => 'Banque de Luxembourg'];
        $list[] = ['min' => 824, 'max' => 824, 'bic' => 'NAV', 'bank' => 'ING Bank'];
        $list[] = ['min' => 825, 'max' => 826, 'bic' => 'DEUT BE BE', 'bank' => 'Deutsche Bank AG'];
        $list[] = ['min' => 827, 'max' => 827, 'bic' => 'ETHI BE BB', 'bank' => 'OPTIMA BANK'];
        $list[] = ['min' => 828, 'max' => 828, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
//         $list[] = ['min' => 829, 'max' => 829, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 830, 'max' => 839, 'bic' => 'GKCC BE BB', 'bank' => 'BELFIUS BANK'];
        $list[] = ['min' => 840, 'max' => 840, 'bic' => 'PRIB BE BB', 'bank' => 'Edmond de Rothschild (Europe)'];
//         $list[] = ['min' => 841, 'max' => 842, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 843, 'max' => 843, 'bic' => 'FTNO BE B1', 'bank' => 'FORTUNEO BELGIUM'];
        $list[] = ['min' => 844, 'max' => 844, 'bic' => 'RABO BE 22', 'bank' => 'Rabobank.be'];
        $list[] = ['min' => 845, 'max' => 845, 'bic' => 'DEGR BE BB', 'bank' => 'Bank Degroof Petercam'];
//         $list[] = ['min' => 846, 'max' => 849, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 850, 'max' => 853, 'bic' => 'SPAA BE 22', 'bank' => 'Crelan'];
//         $list[] = ['min' => 854, 'max' => 857, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 858, 'max' => 858, 'bic' => 'PSAB BE B1', 'bank' => 'PSA Finance'];
        $list[] = ['min' => 859, 'max' => 863, 'bic' => 'SPAA BE 22', 'bank' => 'Crelan'];
        $list[] = ['min' => 864, 'max' => 864, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 865, 'max' => 866, 'bic' => 'SPAA BE 22', 'bank' => 'Crelan'];
//         $list[] = ['min' => 867, 'max' => 867, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 868, 'max' => 868, 'bic' => 'KRED BE BB', 'bank' => 'KBC Bank'];
        $list[] = ['min' => 869, 'max' => 869, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 870, 'max' => 872, 'bic' => 'BNAG BE BB', 'bank' => 'Bank Nagelmackers'];
        $list[] = ['min' => 873, 'max' => 873, 'bic' => 'PCHQ BE BB', 'bank' => 'bpost'];
        $list[] = ['min' => 874, 'max' => 874, 'bic' => 'BNAG BE BB', 'bank' => 'Bank Nagelmackers'];
        $list[] = ['min' => 875, 'max' => 875, 'bic' => 'nav', 'bank' => 'Union Bancaire Privée (Europe)'];
        $list[] = ['min' => 876, 'max' => 876, 'bic' => 'MBWM BE BB', 'bank' => 'MeDirect Bank S.A.'];
        $list[] = ['min' => 877, 'max' => 879, 'bic' => 'BNAG BE BB', 'bank' => 'Bank Nagelmackers'];
        $list[] = ['min' => 880, 'max' => 889, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
        $list[] = ['min' => 890, 'max' => 899, 'bic' => 'VDSP BE 91', 'bank' => 'Volksdepositokas Spaarbank (VDK Spaarbank)'];
        $list[] = ['min' => 900, 'max' => 902, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
//         $list[] = ['min' => 903, 'max' => 905, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 906, 'max' => 906, 'bic' => 'CEKV BE 81', 'bank' => 'Centrale Kredietverlening (C.K.V.)'];
        $list[] = ['min' => 907, 'max' => 907, 'bic' => 'SPAA BE 22', 'bank' => 'Crelan'];
        $list[] = ['min' => 908, 'max' => 908, 'bic' => 'CEKV BE 81', 'bank' => 'Centrale Kredietverlening (C.K.V.)'];
        $list[] = ['min' => 909, 'max' => 909, 'bic' => 'FTNO BE B1', 'bank' => 'FORTUNEO BELGIUM'];
        $list[] = ['min' => 910, 'max' => 910, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
        $list[] = ['min' => 911, 'max' => 911, 'bic' => 'TUNZ BE B1', 'bank' => 'Ingenico Financial Solutions'];
        $list[] = ['min' => 912, 'max' => 912, 'bic' => 'nav', 'bank' => 'Hi - Media Porte Monnaie Electronique'];
        $list[] = ['min' => 913, 'max' => 913, 'bic' => 'EPBF BE BB', 'bank' => 'EPBF'];
        $list[] = ['min' => 914, 'max' => 914, 'bic' => 'FXBBBEBB', 'bank' => 'FX4BIZ'];
//         $list[] = ['min' => 915, 'max' => 915, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 916, 'max' => 916, 'bic' => 'GOCF BE B1', 'bank' => 'GOLD COMMODITIES FOREX (G.C.F.)'];
//         $list[] = ['min' => 917, 'max' => 918, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 919, 'max' => 919, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 920, 'max' => 923, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
//         $list[] = ['min' => 924, 'max' => 924, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 925, 'max' => 925, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
//         $list[] = ['min' => 926, 'max' => 926, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 927, 'max' => 927, 'bic' => 'FETA LU LL BEL', 'bank' => 'RBC Investor Services Bank'];
//         $list[] = ['min' => 928, 'max' => 928, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 929, 'max' => 939, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
        $list[] = ['min' => 940, 'max' => 940, 'bic' => 'CLIQ BE B1', 'bank' => 'Banque Centrale de Compensation (Clearnet)'];
        $list[] = ['min' => 941, 'max' => 941, 'bic' => 'CVMC BE BB', 'bank' => 'C A Indosuez Wealth (Europe)'];
        $list[] = ['min' => 942, 'max' => 942, 'bic' => 'PUIL BE BB', 'bank' => 'Puilaetco Dewaay Private Bankers'];
        $list[] = ['min' => 943, 'max' => 943, 'bic' => 'nav', 'bank' => 'CNH Financial Services SAS'];
        $list[] = ['min' => 944, 'max' => 944, 'bic' => 'NYA', 'bank' => 'J.P. Morgan Europe Ltd .'];
        $list[] = ['min' => 945, 'max' => 945, 'bic' => 'JPMG BE BB', 'bank' => 'J.P. Morgan International Bank Limited'];
//         $list[] = ['min' => 946, 'max' => 946, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 947, 'max' => 947, 'bic' => 'AARB BE B1', 'bank' => 'Aareal Bank - Brussels Branch'];
//         $list[] = ['min' => 948, 'max' => 948, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 949, 'max' => 949, 'bic' => 'HSBC BE BB', 'bank' => 'HSBC Bank'];
        $list[] = ['min' => 950, 'max' => 959, 'bic' => 'CTBK BE BX', 'bank' => 'Beobank'];
        $list[] = ['min' => 960, 'max' => 960, 'bic' => 'ABNA BE 2A IPC', 'bank' => 'ABN AMRO Bank N.V.'];
        $list[] = ['min' => 961, 'max' => 961, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
        $list[] = ['min' => 962, 'max' => 962, 'bic' => 'ETHI BE BB', 'bank' => 'OPTIMA BANK'];
        $list[] = ['min' => 963, 'max' => 963, 'bic' => 'AXAB BE 22', 'bank' => 'AXA Bank Europe'];
        $list[] = ['min' => 964, 'max' => 964, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 965, 'max' => 965, 'bic' => 'ETHI BE BB', 'bank' => 'OPTIMA BANK'];
        $list[] = ['min' => 966, 'max' => 966, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
//         $list[] = ['min' => 967, 'max' => 967, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 968, 'max' => 968, 'bic' => 'ENIB BE BB', 'bank' => ''];
        $list[] = ['min' => 969, 'max' => 969, 'bic' => 'PUIL BE BB', 'bank' => 'Puilaetco Dewaay Private Bankers'];
        $list[] = ['min' => 970, 'max' => 971, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
        $list[] = ['min' => 972, 'max' => 972, 'bic' => 'NAP', 'bank' => 'Onbeschikbaar'];
        $list[] = ['min' => 973, 'max' => 973, 'bic' => 'ARSP BE 22', 'bank' => 'Argenta Spaarbank (ASPA)'];
//         $list[] = ['min' => 974, 'max' => 974, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 975, 'max' => 975, 'bic' => 'AXAB BE 22', 'bank' => 'AXA Bank Europe'];
        $list[] = ['min' => 976, 'max' => 976, 'bic' => 'HBKA BE 22', 'bank' => 'Record Bank'];
//         $list[] = ['min' => 977, 'max' => 977, 'bic' => 'VRIJ', 'bank' => 'VRIJ'];
        $list[] = ['min' => 978, 'max' => 980, 'bic' => 'ARSP BE 22', 'bank' => 'Argenta Spaarbank (ASPA)'];
        $list[] = ['min' => 981, 'max' => 984, 'bic' => 'PCHQ BE BB', 'bank' => 'bpost'];
        $list[] = ['min' => 985, 'max' => 988, 'bic' => 'BPOT BE B1', 'bank' => 'bpost bank'];
//         $list[] = ['min' => 989, 'max' => 989, 'bic' => 'nav', 'bank' => 'bpost'];
//         $list[] = ['min' => 990, 'max' => 999, 'bic' => 'nav', 'bank' => 'Bpost'];
        
        foreach($list as $bank) {
            if($bank['min'] <= $controle && $controle <= $bank['max']) {
                return preg_replace('/[^a-zA-Z0-9]/', '', $bank['bic']);
            }
        }
        
        
        $client = new \SoapClient('http://www.ibanbic.be/IBANBIC.asmx?WSDL');
        $bban = $client->getBelgianBBAN(array('Value' => $iban))->getBelgianBBANResult;
        $bic = $client->BBANtoBIC(array('Value' => $bban))->BBANtoBICResult;
        $bic = preg_replace('/[^a-zA-Z0-9]/', '', $bic);
        return $bic;
    }
}